// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type AgencesDocumentDataSlicesSlice = LocalisationSlice;

/**
 * Content for Agences documents
 */
interface AgencesDocumentData {
  /**
   * Slice Zone field in *Agences*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: agences.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AgencesDocumentDataSlicesSlice>;
}

/**
 * Agences document from Prismic
 *
 * - **API ID**: `agences`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AgencesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<AgencesDocumentData>,
    "agences",
    Lang
  >;

/**
 * Item in *AssuranceLink → Assurances Link*
 */
export interface AssuranceLinkDocumentDataAssurancesLinkItem {
  /**
   * link field in *AssuranceLink → Assurances Link*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link
   * - **API ID Path**: assurance_link.assurances_link[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * description field in *AssuranceLink → Assurances Link*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Description
   * - **API ID Path**: assurance_link.assurances_link[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * icone field in *AssuranceLink → Assurances Link*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: assurance_link.assurances_link[].icone
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icone: prismic.ImageField<never>;
}

/**
 * Content for AssuranceLink documents
 */
interface AssuranceLinkDocumentData {
  /**
   * Assurances Link field in *AssuranceLink*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: assurance_link.assurances_link[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  assurances_link: prismic.GroupField<
    Simplify<AssuranceLinkDocumentDataAssurancesLinkItem>
  >;
}

/**
 * AssuranceLink document from Prismic
 *
 * - **API ID**: `assurance_link`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AssuranceLinkDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<AssuranceLinkDocumentData>,
    "assurance_link",
    Lang
  >;

/**
 * Item in *assurances → Hero*
 */
export interface AssurancesDocumentDataHeroItem {
  /**
   * Image field in *assurances → Hero*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: assurances.hero[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Badge field in *assurances → Hero*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Petit titre présent dans l'encart de l'image
   * - **API ID Path**: assurances.hero[].badge
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  badge: prismic.KeyTextField;

  /**
   * Badge color field in *assurances → Hero*
   *
   * - **Field Type**: Color
   * - **Placeholder**: Couleurs du badge
   * - **API ID Path**: assurances.hero[].badge_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  badge_color: prismic.ColorField;

  /**
   * Long titre field in *assurances → Hero*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Titre présent dans la carte
   * - **API ID Path**: assurances.hero[].titre
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre: prismic.KeyTextField;

  /**
   * Overview field in *assurances → Hero*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Long text présent dans la carte
   * - **API ID Path**: assurances.hero[].overview
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  overview: prismic.RichTextField;

  /**
   * Support text field in *assurances → Hero*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Texte d'appuis en bas de carte
   * - **API ID Path**: assurances.hero[].support_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  support_text: prismic.RichTextField;
}

/**
 * Item in *assurances → Additional content*
 */
export interface AssurancesDocumentDataContentItem {
  /**
   * Content field in *assurances → Additional content*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Texte supplémentaire
   * - **API ID Path**: assurances.content[].content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

type AssurancesDocumentDataSlicesSlice = never;

/**
 * Content for assurances documents
 */
interface AssurancesDocumentData {
  /**
   * Hero field in *assurances*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: assurances.hero[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  hero: prismic.GroupField<Simplify<AssurancesDocumentDataHeroItem>>;

  /**
   * Additional content field in *assurances*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: assurances.content[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  content: prismic.GroupField<Simplify<AssurancesDocumentDataContentItem>>;

  /**
   * Slice Zone field in *assurances*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: assurances.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AssurancesDocumentDataSlicesSlice> /**
   * Meta Title field in *assurances*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: assurances.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *assurances*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: assurances.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *assurances*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: assurances.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * assurances document from Prismic
 *
 * - **API ID**: `assurances`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AssurancesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<AssurancesDocumentData>,
    "assurances",
    Lang
  >;

type CollaboratorsDocumentDataSlicesSlice = CollaboratorsSlice;

/**
 * Content for collaborators documents
 */
interface CollaboratorsDocumentData {
  /**
   * Slice Zone field in *collaborators*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: collaborators.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<CollaboratorsDocumentDataSlicesSlice>;
}

/**
 * collaborators document from Prismic
 *
 * - **API ID**: `collaborators`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CollaboratorsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CollaboratorsDocumentData>,
    "collaborators",
    Lang
  >;

type ContactDocumentDataSlicesSlice = never;

/**
 * Content for contact documents
 */
interface ContactDocumentData {
  /**
   * titre field in *contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Titre
   * - **API ID Path**: contact.titre
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre: prismic.KeyTextField;

  /**
   * Liste Agences field in *contact*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.liste_agences
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  liste_agences: prismic.ContentRelationshipField<"agences">;

  /**
   * Slice Zone field in *contact*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ContactDocumentDataSlicesSlice> /**
   * Meta Title field in *contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: contact.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: contact.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *contact*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * contact document from Prismic
 *
 * - **API ID**: `contact`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ContactDocumentData>,
    "contact",
    Lang
  >;

/**
 * Content for executive_managers documents
 */
interface ExecutiveManagerDocumentData {
  /**
   * name field in *executive_managers*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Nom Prénom
   * - **API ID Path**: executive_manager.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * arrival_date field in *executive_managers*
   *
   * - **Field Type**: Date
   * - **Placeholder**: Date d'arrivée
   * - **API ID Path**: executive_manager.arrival_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  arrival_date: prismic.DateField;

  /**
   * Job title field in *executive_managers*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Job title
   * - **API ID Path**: executive_manager.job_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  job_title: prismic.TitleField;

  /**
   * Job description field in *executive_managers*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Job description
   * - **API ID Path**: executive_manager.job_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  job_description: prismic.RichTextField;

  /**
   * photo field in *executive_managers*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: executive_manager.photo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  photo: prismic.ImageField<never>;
}

/**
 * executive_managers document from Prismic
 *
 * - **API ID**: `executive_manager`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ExecutiveManagerDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ExecutiveManagerDocumentData>,
    "executive_manager",
    Lang
  >;

/**
 * Item in *footer → Columns*
 */
export interface FooterDocumentDataColumnsItem {
  /**
   * Title field in *footer → Columns*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Titre de la colonne
   * - **API ID Path**: footer.columns[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Link field in *footer → Columns*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Lien
   * - **API ID Path**: footer.columns[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

type FooterDocumentDataSlicesSlice = FooterSectionSlice;

/**
 * Content for footer documents
 */
interface FooterDocumentData {
  /**
   * Footer logo field in *footer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.footer_logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  footer_logo: prismic.ImageField<never>;

  /**
   * Footer slogan field in *footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.footer_slogan
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  footer_slogan: prismic.RichTextField;

  /**
   * Columns field in *footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.columns[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  columns: prismic.GroupField<Simplify<FooterDocumentDataColumnsItem>>;

  /**
   * Footer copyright field in *footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.footer_copyright
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  footer_copyright: prismic.KeyTextField;

  /**
   * Legal link field in *footer*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Label du lien
   * - **API ID Path**: footer.legal_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  legal_link: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * Slice Zone field in *footer*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<FooterDocumentDataSlicesSlice>;
}

/**
 * footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

type HomeDocumentDataSlicesSlice =
  | AnnoncesSlice
  | ContactSlice
  | NumbersSlice
  | LocalisationSlice
  | ExecutivesSlice
  | CartesAssurancesSlice
  | MembershipSliderSlice
  | HeroMosaicImagesSlice;

/**
 * Content for home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Title field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

/**
 * Item in *menu → Assurances*
 */
export interface MenuDocumentDataAssurancesBisItem {
  /**
   * Label field in *menu → Assurances*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Label
   * - **API ID Path**: menu.assurances_bis[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Assurance link field in *menu → Assurances*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.assurances_bis[].assurance_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  assurance_link: prismic.ContentRelationshipField<"assurance_link">;
}

type MenuDocumentDataSlices1Slice = MenuLinkSlice;

/**
 * Content for menu documents
 */
interface MenuDocumentData {
  /**
   * home field in *menu*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Assurance
   * - **API ID Path**: menu.home_bis
   * - **Tab**: Menu bis
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  home_bis: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Assurances field in *menu*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.assurances_bis[]
   * - **Tab**: Menu bis
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  assurances_bis: prismic.GroupField<
    Simplify<MenuDocumentDataAssurancesBisItem>
  >;

  /**
   * Contact field in *menu*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Contact
   * - **API ID Path**: menu.contact_bis
   * - **Tab**: Menu bis
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  contact_bis: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Nous connaître field in *menu*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Nous connaître
   * - **API ID Path**: menu.nous_connaitre_bis
   * - **Tab**: Menu bis
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  nous_connaitre_bis: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Slice Zone field in *menu*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.slices1[]
   * - **Tab**: Menu bis
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices1: prismic.SliceZone<MenuDocumentDataSlices1Slice>;
}

/**
 * menu document from Prismic
 *
 * - **API ID**: `menu`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MenuDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<MenuDocumentData>, "menu", Lang>;

/**
 * Item in *nous connaitre → Hero*
 */
export interface NousConnaitreDocumentDataHeroItem {
  /**
   * Image field in *nous connaitre → Hero*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: nous_connaitre.hero[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *nous connaitre → Hero*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Titre de la Hero
   * - **API ID Path**: nous_connaitre.hero[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Catchphrase field in *nous connaitre → Hero*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Phrase d'accroche
   * - **API ID Path**: nous_connaitre.hero[].catchphrase
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  catchphrase: prismic.KeyTextField;
}

/**
 * Item in *nous connaitre → Content*
 */
export interface NousConnaitreDocumentDataContentItem {
  /**
   * Content field in *nous connaitre → Content*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Contenue de la page
   * - **API ID Path**: nous_connaitre.content[].content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

type NousConnaitreDocumentDataSlicesSlice = MembershipSliderSlice;

/**
 * Content for nous connaitre documents
 */
interface NousConnaitreDocumentData {
  /**
   * Hero field in *nous connaitre*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: nous_connaitre.hero[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  hero: prismic.GroupField<Simplify<NousConnaitreDocumentDataHeroItem>>;

  /**
   * Content field in *nous connaitre*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: nous_connaitre.content[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  content: prismic.GroupField<Simplify<NousConnaitreDocumentDataContentItem>>;

  /**
   * Slice Zone field in *nous connaitre*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: nous_connaitre.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<NousConnaitreDocumentDataSlicesSlice> /**
   * Meta Title field in *nous connaitre*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: nous_connaitre.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *nous connaitre*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: nous_connaitre.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *nous connaitre*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: nous_connaitre.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * nous connaitre document from Prismic
 *
 * - **API ID**: `nous_connaitre`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NousConnaitreDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NousConnaitreDocumentData>,
    "nous_connaitre",
    Lang
  >;

export type AllDocumentTypes =
  | AgencesDocument
  | AssuranceLinkDocument
  | AssurancesDocument
  | CollaboratorsDocument
  | ContactDocument
  | ExecutiveManagerDocument
  | FooterDocument
  | HomeDocument
  | MenuDocument
  | NousConnaitreDocument;

/**
 * Primary content in *Annonces → Default → Primary*
 */
export interface AnnoncesSliceDefaultPrimary {
  /**
   * Couleur field in *Annonces → Default → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: Couleur du background de l'annonce
   * - **API ID Path**: annonces.default.primary.background
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  background: prismic.ColorField;

  /**
   * Texte field in *Annonces → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Le text de l'annonce
   * - **API ID Path**: annonces.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Bouton field in *Annonces → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Lien par bouton
   * - **API ID Path**: annonces.default.primary.button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for Annonces Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AnnoncesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AnnoncesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Annonces*
 */
type AnnoncesSliceVariation = AnnoncesSliceDefault;

/**
 * Annonces Shared Slice
 *
 * - **API ID**: `annonces`
 * - **Description**: Annonces
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AnnoncesSlice = prismic.SharedSlice<
  "annonces",
  AnnoncesSliceVariation
>;

/**
 * Item in *CartesAssurances → Default → Primary → Cartes*
 */
export interface CartesAssurancesSliceDefaultPrimaryCardsItem {
  /**
   * Logo field in *CartesAssurances → Default → Primary → Cartes*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cartes_assurances.default.primary.cards[].logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Titre field in *CartesAssurances → Default → Primary → Cartes*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Titre
   * - **API ID Path**: cartes_assurances.default.primary.cards[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Description field in *CartesAssurances → Default → Primary → Cartes*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Description (courte: 3 ou 4 mots)
   * - **API ID Path**: cartes_assurances.default.primary.cards[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Primary content in *CartesAssurances → Default → Primary*
 */
export interface CartesAssurancesSliceDefaultPrimary {
  /**
   * Titre field in *CartesAssurances → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Title
   * - **API ID Path**: cartes_assurances.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *CartesAssurances → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Description
   * - **API ID Path**: cartes_assurances.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Cartes field in *CartesAssurances → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: cartes_assurances.default.primary.cards[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  cards: prismic.GroupField<
    Simplify<CartesAssurancesSliceDefaultPrimaryCardsItem>
  >;
}

/**
 * Default variation for CartesAssurances Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CartesAssurancesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CartesAssurancesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CartesAssurances*
 */
type CartesAssurancesSliceVariation = CartesAssurancesSliceDefault;

/**
 * CartesAssurances Shared Slice
 *
 * - **API ID**: `cartes_assurances`
 * - **Description**: CartesAssurances
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CartesAssurancesSlice = prismic.SharedSlice<
  "cartes_assurances",
  CartesAssurancesSliceVariation
>;

/**
 * Primary content in *Collaborators → Default → Primary*
 */
export interface CollaboratorsSliceDefaultPrimary {
  /**
   * Photo field in *Collaborators → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: collaborators.default.primary.photo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  photo: prismic.ImageField<never>;

  /**
   * Nom field in *Collaborators → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Nom Prénom
   * - **API ID Path**: collaborators.default.primary.name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.RichTextField;

  /**
   * Job field in *Collaborators → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Job
   * - **API ID Path**: collaborators.default.primary.job
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  job: prismic.RichTextField;

  /**
   * Arrival date field in *Collaborators → Default → Primary*
   *
   * - **Field Type**: Date
   * - **Placeholder**: Date d'entrée dans l'entreprise
   * - **API ID Path**: collaborators.default.primary.arrival_date
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  arrival_date: prismic.DateField;

  /**
   * Description field in *Collaborators → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Présentation du collaborateur
   * - **API ID Path**: collaborators.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for Collaborators Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CollaboratorsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CollaboratorsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Collaborators*
 */
type CollaboratorsSliceVariation = CollaboratorsSliceDefault;

/**
 * Collaborators Shared Slice
 *
 * - **API ID**: `collaborators`
 * - **Description**: Collaborators
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CollaboratorsSlice = prismic.SharedSlice<
  "collaborators",
  CollaboratorsSliceVariation
>;

/**
 * Primary content in *Contact → Default → Primary*
 */
export interface ContactSliceDefaultPrimary {
  /**
   * Titre field in *Contact → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Titre
   * - **API ID Path**: contact.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Description field in *Contact → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: description
   * - **API ID Path**: contact.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Link field in *Contact → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link
   * - **API ID Path**: contact.default.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    "primary" | "secondary"
  >;
}

/**
 * Default variation for Contact Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Contact*
 */
type ContactSliceVariation = ContactSliceDefault;

/**
 * Contact Shared Slice
 *
 * - **API ID**: `contact`
 * - **Description**: Contact
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactSlice = prismic.SharedSlice<
  "contact",
  ContactSliceVariation
>;

/**
 * Item in *Executives → Default → Primary → executives*
 */
export interface ExecutivesSliceDefaultPrimaryExecutivesItem {
  /**
   * executives field in *Executives → Default → Primary → executives*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: executives.default.primary.executives[].executives
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  executives: prismic.ContentRelationshipField<"executive_manager">;
}

/**
 * Primary content in *Executives → Default → Primary*
 */
export interface ExecutivesSliceDefaultPrimary {
  /**
   * executives field in *Executives → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: executives.default.primary.executives[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  executives: prismic.GroupField<
    Simplify<ExecutivesSliceDefaultPrimaryExecutivesItem>
  >;
}

/**
 * Default variation for Executives Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ExecutivesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ExecutivesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Executives*
 */
type ExecutivesSliceVariation = ExecutivesSliceDefault;

/**
 * Executives Shared Slice
 *
 * - **API ID**: `executives`
 * - **Description**: Executives
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ExecutivesSlice = prismic.SharedSlice<
  "executives",
  ExecutivesSliceVariation
>;

/**
 * Item in *FooterSection → Socials → Primary → Section links*
 */
export interface FooterSectionSliceSocialsPrimarySectionLinksItem {
  /**
   * Section link icon field in *FooterSection → Socials → Primary → Section links*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_section.socials.primary.section_links[].section_link_icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  section_link_icon: prismic.ImageField<never>;

  /**
   * Section link url field in *FooterSection → Socials → Primary → Section links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_section.socials.primary.section_links[].section_link_url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  section_link_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *FooterSection → Socials → Primary*
 */
export interface FooterSectionSliceSocialsPrimary {
  /**
   * Section links field in *FooterSection → Socials → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer_section.socials.primary.section_links[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  section_links: prismic.GroupField<
    Simplify<FooterSectionSliceSocialsPrimarySectionLinksItem>
  >;
}

/**
 * Socials variation for FooterSection Slice
 *
 * - **API ID**: `socials`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterSectionSliceSocials = prismic.SharedSliceVariation<
  "socials",
  Simplify<FooterSectionSliceSocialsPrimary>,
  never
>;

/**
 * Slice variation for *FooterSection*
 */
type FooterSectionSliceVariation = FooterSectionSliceSocials;

/**
 * FooterSection Shared Slice
 *
 * - **API ID**: `footer_section`
 * - **Description**: FooterSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterSectionSlice = prismic.SharedSlice<
  "footer_section",
  FooterSectionSliceVariation
>;

/**
 * Item in *HeroMosaicImages → Default → Primary → Images*
 */
export interface HeroMosaicImagesSliceDefaultPrimaryImagesItem {
  /**
   * Image field in *HeroMosaicImages → Default → Primary → Images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_mosaic_images.default.primary.images[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Titre image field in *HeroMosaicImages → Default → Primary → Images*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Titre image
   * - **API ID Path**: hero_mosaic_images.default.primary.images[].image_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  image_title: prismic.RichTextField;

  /**
   * Sous titre image field in *HeroMosaicImages → Default → Primary → Images*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Sous titre image
   * - **API ID Path**: hero_mosaic_images.default.primary.images[].image_sub_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  image_sub_title: prismic.RichTextField;
}

/**
 * Primary content in *HeroMosaicImages → Default → Primary*
 */
export interface HeroMosaicImagesSliceDefaultPrimary {
  /**
   * Titre field in *HeroMosaicImages → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Titre
   * - **API ID Path**: hero_mosaic_images.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Sous titre field in *HeroMosaicImages → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Sous titre
   * - **API ID Path**: hero_mosaic_images.default.primary.sub_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_title: prismic.RichTextField;

  /**
   * Bouton field in *HeroMosaicImages → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Bouton
   * - **API ID Path**: hero_mosaic_images.default.primary.button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    "primary" | "secondary"
  >;

  /**
   * Images field in *HeroMosaicImages → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_mosaic_images.default.primary.images[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  images: prismic.GroupField<
    Simplify<HeroMosaicImagesSliceDefaultPrimaryImagesItem>
  >;
}

/**
 * Default variation for HeroMosaicImages Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroMosaicImagesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroMosaicImagesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroMosaicImages*
 */
type HeroMosaicImagesSliceVariation = HeroMosaicImagesSliceDefault;

/**
 * HeroMosaicImages Shared Slice
 *
 * - **API ID**: `hero_mosaic_images`
 * - **Description**: HeroMosaicImages
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroMosaicImagesSlice = prismic.SharedSlice<
  "hero_mosaic_images",
  HeroMosaicImagesSliceVariation
>;

/**
 * Item in *Localisation → Default → Primary → Content*
 */
export interface LocalisationSliceDefaultPrimaryContentItem {
  /**
   * Info field in *Localisation → Default → Primary → Content*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Informations concernant l'agence
   * - **API ID Path**: localisation.default.primary.content[].info
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  info: prismic.RichTextField;
}

/**
 * Primary content in *Localisation → Default → Primary*
 */
export interface LocalisationSliceDefaultPrimary {
  /**
   * Content field in *Localisation → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: localisation.default.primary.content[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  content: prismic.GroupField<
    Simplify<LocalisationSliceDefaultPrimaryContentItem>
  >;

  /**
   * titre field in *Localisation → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Titre
   * - **API ID Path**: localisation.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Adresse field in *Localisation → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Adresse
   * - **API ID Path**: localisation.default.primary.address
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  address: prismic.RichTextField;

  /**
   * Image field in *Localisation → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: localisation.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for Localisation Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LocalisationSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LocalisationSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Localisation*
 */
type LocalisationSliceVariation = LocalisationSliceDefault;

/**
 * Localisation Shared Slice
 *
 * - **API ID**: `localisation`
 * - **Description**: Localisation
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LocalisationSlice = prismic.SharedSlice<
  "localisation",
  LocalisationSliceVariation
>;

/**
 * Primary content in *Memberships → Default → Primary*
 */
export interface MembershipSliderSliceDefaultPrimary {
  /**
   * Titre field in *Memberships → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Titre
   * - **API ID Path**: membership_slider.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *Memberships → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Description
   * - **API ID Path**: membership_slider.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Collaborateurs field in *Memberships → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: membership_slider.default.primary.collaborators
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  collaborators: prismic.ContentRelationshipField<"collaborators">;
}

/**
 * Default variation for Memberships Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MembershipSliderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MembershipSliderSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Memberships → No text → Primary*
 */
export interface MembershipSliderSliceNoTextPrimary {
  /**
   * Collaborateurs field in *Memberships → No text → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: membership_slider.noText.primary.collaborators
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  collaborators: prismic.ContentRelationshipField<"collaborators">;
}

/**
 * No text variation for Memberships Slice
 *
 * - **API ID**: `noText`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MembershipSliderSliceNoText = prismic.SharedSliceVariation<
  "noText",
  Simplify<MembershipSliderSliceNoTextPrimary>,
  never
>;

/**
 * Slice variation for *Memberships*
 */
type MembershipSliderSliceVariation =
  | MembershipSliderSliceDefault
  | MembershipSliderSliceNoText;

/**
 * Memberships Shared Slice
 *
 * - **API ID**: `membership_slider`
 * - **Description**: Memberships
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MembershipSliderSlice = prismic.SharedSlice<
  "membership_slider",
  MembershipSliderSliceVariation
>;

/**
 * Primary content in *MenuLink → Default → Primary*
 */
export interface MenuLinkSliceDefaultPrimary {
  /**
   * description field in *MenuLink → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Description
   * - **API ID Path**: menu_link.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * sub_description field in *MenuLink → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Sub description
   * - **API ID Path**: menu_link.default.primary.sub_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sub_description: prismic.RichTextField;

  /**
   * Link field in *MenuLink → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link
   * - **API ID Path**: menu_link.default.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    "primary" | "secondary"
  >;
}

/**
 * Default variation for MenuLink Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MenuLinkSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MenuLinkSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *MenuLink*
 */
type MenuLinkSliceVariation = MenuLinkSliceDefault;

/**
 * MenuLink Shared Slice
 *
 * - **API ID**: `menu_link`
 * - **Description**: MenuLink
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MenuLinkSlice = prismic.SharedSlice<
  "menu_link",
  MenuLinkSliceVariation
>;

/**
 * Item in *Numbers → TwoNumbers → Primary → TwoNumbers*
 */
export interface NumbersSliceTwoNumbersPrimaryTwonumbersItem {
  /**
   * number field in *Numbers → TwoNumbers → Primary → TwoNumbers*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: First Number
   * - **API ID Path**: numbers.twoNumbers.primary.twonumbers[].first_number
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  first_number: prismic.RichTextField;

  /**
   * First Description field in *Numbers → TwoNumbers → Primary → TwoNumbers*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: First Description
   * - **API ID Path**: numbers.twoNumbers.primary.twonumbers[].first_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  first_description: prismic.RichTextField;

  /**
   * number field in *Numbers → TwoNumbers → Primary → TwoNumbers*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Second Number
   * - **API ID Path**: numbers.twoNumbers.primary.twonumbers[].second_number
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  second_number: prismic.RichTextField;

  /**
   * Second Description field in *Numbers → TwoNumbers → Primary → TwoNumbers*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Second Description
   * - **API ID Path**: numbers.twoNumbers.primary.twonumbers[].second_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  second_description: prismic.RichTextField;
}

/**
 * Item in *Numbers → ThreeNumbers → Primary → ThreeNumbers*
 */
export interface NumbersSliceThreeNumbersPrimaryThreenumbersItem {
  /**
   * First Number field in *Numbers → ThreeNumbers → Primary → ThreeNumbers*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: First Number
   * - **API ID Path**: numbers.threeNumbers.primary.threenumbers[].first_number
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  first_number: prismic.RichTextField;

  /**
   * First Description field in *Numbers → ThreeNumbers → Primary → ThreeNumbers*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: First Description
   * - **API ID Path**: numbers.threeNumbers.primary.threenumbers[].first_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  first_description: prismic.RichTextField;

  /**
   * Second Number field in *Numbers → ThreeNumbers → Primary → ThreeNumbers*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Second Number
   * - **API ID Path**: numbers.threeNumbers.primary.threenumbers[].second_number
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  second_number: prismic.RichTextField;

  /**
   * Second Description field in *Numbers → ThreeNumbers → Primary → ThreeNumbers*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Second Description
   * - **API ID Path**: numbers.threeNumbers.primary.threenumbers[].second_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  second_description: prismic.RichTextField;

  /**
   * Third Number field in *Numbers → ThreeNumbers → Primary → ThreeNumbers*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Third Number
   * - **API ID Path**: numbers.threeNumbers.primary.threenumbers[].third_number
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  third_number: prismic.RichTextField;

  /**
   * Third Description field in *Numbers → ThreeNumbers → Primary → ThreeNumbers*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Third Description
   * - **API ID Path**: numbers.threeNumbers.primary.threenumbers[].third_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  third_description: prismic.RichTextField;
}

/**
 * Primary content in *Numbers → Default → Primary*
 */
export interface NumbersSliceDefaultPrimary {
  /**
   * Chiffre field in *Numbers → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Chiffre
   * - **API ID Path**: numbers.default.primary.number
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  number: prismic.RichTextField;

  /**
   * Description field in *Numbers → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Description
   * - **API ID Path**: numbers.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for Numbers Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NumbersSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NumbersSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Numbers → TwoNumbers → Primary*
 */
export interface NumbersSliceTwoNumbersPrimary {
  /**
   * TwoNumbers field in *Numbers → TwoNumbers → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: numbers.twoNumbers.primary.twonumbers[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  twonumbers: prismic.GroupField<
    Simplify<NumbersSliceTwoNumbersPrimaryTwonumbersItem>
  >;
}

/**
 * TwoNumbers variation for Numbers Slice
 *
 * - **API ID**: `twoNumbers`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NumbersSliceTwoNumbers = prismic.SharedSliceVariation<
  "twoNumbers",
  Simplify<NumbersSliceTwoNumbersPrimary>,
  never
>;

/**
 * Primary content in *Numbers → ThreeNumbers → Primary*
 */
export interface NumbersSliceThreeNumbersPrimary {
  /**
   * ThreeNumbers field in *Numbers → ThreeNumbers → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: numbers.threeNumbers.primary.threenumbers[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  threenumbers: prismic.GroupField<
    Simplify<NumbersSliceThreeNumbersPrimaryThreenumbersItem>
  >;
}

/**
 * ThreeNumbers variation for Numbers Slice
 *
 * - **API ID**: `threeNumbers`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NumbersSliceThreeNumbers = prismic.SharedSliceVariation<
  "threeNumbers",
  Simplify<NumbersSliceThreeNumbersPrimary>,
  never
>;

/**
 * Slice variation for *Numbers*
 */
type NumbersSliceVariation =
  | NumbersSliceDefault
  | NumbersSliceTwoNumbers
  | NumbersSliceThreeNumbers;

/**
 * Numbers Shared Slice
 *
 * - **API ID**: `numbers`
 * - **Description**: Numbers
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NumbersSlice = prismic.SharedSlice<
  "numbers",
  NumbersSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AgencesDocument,
      AgencesDocumentData,
      AgencesDocumentDataSlicesSlice,
      AssuranceLinkDocument,
      AssuranceLinkDocumentData,
      AssuranceLinkDocumentDataAssurancesLinkItem,
      AssurancesDocument,
      AssurancesDocumentData,
      AssurancesDocumentDataHeroItem,
      AssurancesDocumentDataContentItem,
      AssurancesDocumentDataSlicesSlice,
      CollaboratorsDocument,
      CollaboratorsDocumentData,
      CollaboratorsDocumentDataSlicesSlice,
      ContactDocument,
      ContactDocumentData,
      ContactDocumentDataSlicesSlice,
      ExecutiveManagerDocument,
      ExecutiveManagerDocumentData,
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataColumnsItem,
      FooterDocumentDataSlicesSlice,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      MenuDocument,
      MenuDocumentData,
      MenuDocumentDataAssurancesBisItem,
      MenuDocumentDataSlices1Slice,
      NousConnaitreDocument,
      NousConnaitreDocumentData,
      NousConnaitreDocumentDataHeroItem,
      NousConnaitreDocumentDataContentItem,
      NousConnaitreDocumentDataSlicesSlice,
      AllDocumentTypes,
      AnnoncesSlice,
      AnnoncesSliceDefaultPrimary,
      AnnoncesSliceVariation,
      AnnoncesSliceDefault,
      CartesAssurancesSlice,
      CartesAssurancesSliceDefaultPrimaryCardsItem,
      CartesAssurancesSliceDefaultPrimary,
      CartesAssurancesSliceVariation,
      CartesAssurancesSliceDefault,
      CollaboratorsSlice,
      CollaboratorsSliceDefaultPrimary,
      CollaboratorsSliceVariation,
      CollaboratorsSliceDefault,
      ContactSlice,
      ContactSliceDefaultPrimary,
      ContactSliceVariation,
      ContactSliceDefault,
      ExecutivesSlice,
      ExecutivesSliceDefaultPrimaryExecutivesItem,
      ExecutivesSliceDefaultPrimary,
      ExecutivesSliceVariation,
      ExecutivesSliceDefault,
      FooterSectionSlice,
      FooterSectionSliceSocialsPrimarySectionLinksItem,
      FooterSectionSliceSocialsPrimary,
      FooterSectionSliceVariation,
      FooterSectionSliceSocials,
      HeroMosaicImagesSlice,
      HeroMosaicImagesSliceDefaultPrimaryImagesItem,
      HeroMosaicImagesSliceDefaultPrimary,
      HeroMosaicImagesSliceVariation,
      HeroMosaicImagesSliceDefault,
      LocalisationSlice,
      LocalisationSliceDefaultPrimaryContentItem,
      LocalisationSliceDefaultPrimary,
      LocalisationSliceVariation,
      LocalisationSliceDefault,
      MembershipSliderSlice,
      MembershipSliderSliceDefaultPrimary,
      MembershipSliderSliceNoTextPrimary,
      MembershipSliderSliceVariation,
      MembershipSliderSliceDefault,
      MembershipSliderSliceNoText,
      MenuLinkSlice,
      MenuLinkSliceDefaultPrimary,
      MenuLinkSliceVariation,
      MenuLinkSliceDefault,
      NumbersSlice,
      NumbersSliceDefaultPrimary,
      NumbersSliceTwoNumbersPrimaryTwonumbersItem,
      NumbersSliceTwoNumbersPrimary,
      NumbersSliceThreeNumbersPrimaryThreenumbersItem,
      NumbersSliceThreeNumbersPrimary,
      NumbersSliceVariation,
      NumbersSliceDefault,
      NumbersSliceTwoNumbers,
      NumbersSliceThreeNumbers,
    };
  }
}
