// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *menu → Assurances*
 */
export interface MenuDocumentDataAssurancesItem {
  /**
   * label field in *menu → Assurances*
   *
   * - **Field Type**: Text
   * - **Placeholder**: assurances
   * - **API ID Path**: menu.assurances[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * auto field in *menu → Assurances*
   *
   * - **Field Type**: Link
   * - **Placeholder**: auto
   * - **API ID Path**: menu.assurances[].auto
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  auto: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * maison field in *menu → Assurances*
   *
   * - **Field Type**: Link
   * - **Placeholder**: maison
   * - **API ID Path**: menu.assurances[].maison
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  maison: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for menu documents
 */
interface MenuDocumentData {
  /**
   * Assurances field in *menu*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.assurances[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  assurances: prismic.GroupField<Simplify<MenuDocumentDataAssurancesItem>>;

  /**
   * contact field in *menu*
   *
   * - **Field Type**: Link
   * - **Placeholder**: contact
   * - **API ID Path**: menu.contact
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  contact: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * nous connaitre field in *menu*
   *
   * - **Field Type**: Link
   * - **Placeholder**: nous connaitre
   * - **API ID Path**: menu.nous_connaitre
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  nous_connaitre: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * menu document from Prismic
 *
 * - **API ID**: `menu`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MenuDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<MenuDocumentData>, "menu", Lang>;

export type AllDocumentTypes = MenuDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      MenuDocument,
      MenuDocumentData,
      MenuDocumentDataAssurancesItem,
      AllDocumentTypes,
    };
  }
}
