// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type AssurancesDocumentDataSlicesSlice = never;

/**
 * Content for assurances documents
 */
interface AssurancesDocumentData {
  /**
   * Titre field in *assurances*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Titre
   * - **API ID Path**: assurances.titre
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre: prismic.KeyTextField;

  /**
   * Slice Zone field in *assurances*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: assurances.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AssurancesDocumentDataSlicesSlice> /**
   * Meta Title field in *assurances*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: assurances.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *assurances*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: assurances.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *assurances*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: assurances.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * assurances document from Prismic
 *
 * - **API ID**: `assurances`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AssurancesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<AssurancesDocumentData>,
    "assurances",
    Lang
  >;

type ContactDocumentDataSlicesSlice = never;

/**
 * Content for contact documents
 */
interface ContactDocumentData {
  /**
   * titre field in *contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Titre
   * - **API ID Path**: contact.titre
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre: prismic.KeyTextField;

  /**
   * Slice Zone field in *contact*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ContactDocumentDataSlicesSlice> /**
   * Meta Title field in *contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: contact.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: contact.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *contact*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * contact document from Prismic
 *
 * - **API ID**: `contact`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ContactDocumentData>,
    "contact",
    Lang
  >;

type HomeDocumentDataSlicesSlice = never;

/**
 * Content for home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Title field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

/**
 * Item in *menu → Assurances*
 */
export interface MenuDocumentDataAssurancesItem {
  /**
   * label field in *menu → Assurances*
   *
   * - **Field Type**: Text
   * - **Placeholder**: assurances
   * - **API ID Path**: menu.assurances[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * auto field in *menu → Assurances*
   *
   * - **Field Type**: Link
   * - **Placeholder**: auto
   * - **API ID Path**: menu.assurances[].auto
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  auto: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * maison field in *menu → Assurances*
   *
   * - **Field Type**: Link
   * - **Placeholder**: maison
   * - **API ID Path**: menu.assurances[].maison
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  maison: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for menu documents
 */
interface MenuDocumentData {
  /**
   * home field in *menu*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Accueil
   * - **API ID Path**: menu.home
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  home: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Assurances field in *menu*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.assurances[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  assurances: prismic.GroupField<Simplify<MenuDocumentDataAssurancesItem>>;

  /**
   * contact field in *menu*
   *
   * - **Field Type**: Link
   * - **Placeholder**: contact
   * - **API ID Path**: menu.contact
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  contact: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * nous connaitre field in *menu*
   *
   * - **Field Type**: Link
   * - **Placeholder**: nous connaitre
   * - **API ID Path**: menu.nous_connaitre
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  nous_connaitre: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * menu document from Prismic
 *
 * - **API ID**: `menu`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MenuDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<MenuDocumentData>, "menu", Lang>;

type NousConnaitreDocumentDataSlicesSlice = never;

/**
 * Content for nous connaitre documents
 */
interface NousConnaitreDocumentData {
  /**
   * titre field in *nous connaitre*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Titre
   * - **API ID Path**: nous_connaitre.titre
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre: prismic.KeyTextField;

  /**
   * Slice Zone field in *nous connaitre*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: nous_connaitre.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<NousConnaitreDocumentDataSlicesSlice> /**
   * Meta Title field in *nous connaitre*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: nous_connaitre.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *nous connaitre*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: nous_connaitre.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *nous connaitre*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: nous_connaitre.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * nous connaitre document from Prismic
 *
 * - **API ID**: `nous_connaitre`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NousConnaitreDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NousConnaitreDocumentData>,
    "nous_connaitre",
    Lang
  >;

export type AllDocumentTypes =
  | AssurancesDocument
  | ContactDocument
  | HomeDocument
  | MenuDocument
  | NousConnaitreDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AssurancesDocument,
      AssurancesDocumentData,
      AssurancesDocumentDataSlicesSlice,
      ContactDocument,
      ContactDocumentData,
      ContactDocumentDataSlicesSlice,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      MenuDocument,
      MenuDocumentData,
      MenuDocumentDataAssurancesItem,
      NousConnaitreDocument,
      NousConnaitreDocumentData,
      NousConnaitreDocumentDataSlicesSlice,
      AllDocumentTypes,
    };
  }
}
